In [1]:
import numpy as np

In [2]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.linspace(0,10,2)

array([ 0., 10.])

In [8]:
np.random.rand(5,4)

array([[0.48387089, 0.55435802, 0.16883542, 0.4348387 ],
       [0.07197402, 0.36073798, 0.39129811, 0.27933322],
       [0.1024204 , 0.93302737, 0.85570789, 0.52907534],
       [0.6237679 , 0.98434901, 0.75132991, 0.64541974],
       [0.21191925, 0.24873566, 0.55822159, 0.44349541]])

In [10]:
arr = np.arange(0,30,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
arr[3]
arr[2:5]

array([ 6,  9, 12])

In [12]:
arr.shape

(10,)

In [18]:
arr = arr.reshape(2,5)

In [22]:
arr[0]

array([ 0,  3,  6,  9, 12])

In [23]:
arr2 = arr[0]
arr2

array([ 0,  3,  6,  9, 12])

In [24]:
arr2[:2] =100
arr2

array([100, 100,   6,   9,  12])

In [25]:
arr

array([[100, 100,   6,   9,  12],
       [ 15,  18,  21,  24,  27]])

In [26]:
arr3 = arr[0].copy()
arr3

array([100, 100,   6,   9,  12])

In [27]:
arr3[:2] = 200
arr3

array([200, 200,   6,   9,  12])

In [28]:
arr


array([[100, 100,   6,   9,  12],
       [ 15,  18,  21,  24,  27]])

In [30]:
arr[0,0:3]

array([100, 100,   6])

In [31]:
bol = arr>50
bol

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [32]:
arr[bol]

array([100, 100])

In [33]:
arr

array([[100, 100,   6,   9,  12],
       [ 15,  18,  21,  24,  27]])

In [34]:
arr+arr

array([[200, 200,  12,  18,  24],
       [ 30,  36,  42,  48,  54]])

In [35]:
arr-arr


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])